### PR TITLE
remove env.sh

### PR DESCRIPTION
**Pull request by K41R1**
hi,
i suggest to use composer script [https://getcomposer.org/doc/articles/scripts.md#writing-custom-commands](url) instead of redefining the global variable __$PATH__

### CODE REVIEW

**Comment by nulpunkt** [comment]
Hey,

That's a great idea! Could you please fix the indentation under `require-dev`?
I'd be more than happy to merge this.

**Comment by K41R1** [comment]
Hi,
i will fix later..
i also suggest to migrate to phpunit 6.5 **it's a stable release**

**Comment by nulpunkt** [comment]
Yeah, I should probably upgrade phpunit as well :)

**Comment by nulpunkt** [comment]
I'm closing this now, please feel free to return with another pr!

**Pull request closed without merging**
